version: '3.8'

services:
  # Redis para caché y rate limiting
  redis:
    image: redis:7-alpine
    container_name: vambeai-redis
    command: redis-server --requirepass your-redis-password
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - vambeai-network

  # Weaviate para búsqueda vectorial
  weaviate:
    image: semitechnologies/weaviate:1.19.0
    container_name: vambeai-weaviate
    environment:
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      DEFAULT_VECTORIZER_MODULE: 'text2vec-openai'
      ENABLE_MODULES: 'text2vec-openai'
      CLUSTER_HOSTNAME: 'node1'
      QUERY_DEFAULTS_LIMIT: 25
    ports:
      - "8080:8080"
    volumes:
      - weaviate_data:/var/lib/weaviate
    restart: unless-stopped
    networks:
      - vambeai-network

  # MinIO para almacenamiento de archivos
  minio:
    image: minio/minio:RELEASE.2023-07-21T21-12-50Z
    container_name: vambeai-minio
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped
    networks:
      - vambeai-network

networks:
  vambeai-network:
    driver: bridge

volumes:
  redis_data:
  weaviate_data:
  minio_data:
